/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GetStart: typeof import('./src/views/GetStart.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LandingPage: typeof import('./src/views/LandingPage.vue')['default']
    Loved: typeof import('./src/views/Loved.vue')['default']
    LovedCard: typeof import('./src/views/components/LovedCard.vue')['default']
    Price: typeof import('./src/views/Price.vue')['default']
    PriceCard: typeof import('./src/views/components/PriceCard.vue')['default']
    QuestionCard: typeof import('./src/views/components/QuestionCard.vue')['default']
    Questions: typeof import('./src/views/Questions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplifyTasks: typeof import('./src/views/SimplifyTasks.vue')['default']
    SimplifyTasksCardLg: typeof import('./src/views/components/SimplifyTasksCardLg.vue')['default']
    SimplifyTasksCardSm: typeof import('./src/views/components/SimplifyTasksCardSm.vue')['default']
    Synopsis: typeof import('./src/views/Synopsis.vue')['default']
  }
}
